name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'doc/*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build information
        run: 'make info'

      - name: Create the project file needed by setup-pixi
        run: 'make pyproject.toml'

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.45.0

      - name: Run tests
        run: 'make test'
